default: &DEFAULT

  #General
  # For computing compression
  n_params_baseline: None
  verbose: True
  arch: tfno


  #Distributed computing
  distributed:
    use_distributed: 0 #False in darcy
    wireup_info: 'mpi'
    wireup_store: 'tcp'
    model_parallel_size: 1 #2
    seed: 666

  # FNO related
  tfno:
    n_modes: [8,48,48] #for t,x
    data_channels: None #will be determined by pde-onfo, see config_arch in main_code #1(pde)+1(dim:postion)  (i.e. in_channels, but should use the name data_ here (model_dispatcher L55))
    hidden_channels: 28
    projection_channels: 64
    n_layers: 4
    domain_padding: [0.125,0,0] #None #0.078125 #None
    domain_padding_mode: 'one-sided' #symmetric
    fft_norm: 'forward'
    norm: 'group_norm'
    skip: 'linear'
    implementation: 'factorized'
    separable: 0
    preactivation: 0
    
    use_mlp: 1
    mlp:
        expansion: 0.5
        dropout: 0

    factorization: None #'cp' if use factoriz #None
    rank: 1 #1.0
    fixed_rank_modes: None
    dropout: 0.0
    tensor_lasso_penalty: 0.0
    joint_factorization: False
    fno_block_precision: 'full' # or 'half', 'mixed'
    stabilizer: None # or 'tanh'

    check_mem: 0 #if true, print cuda mem
    save_mem: 0 #True # use peak-mem reduction or not
    no_splt: 1 # (default=False) when save_mem=0, if no_split, will override all the split below and no loop-separation is conducted

    block_dvc: [0,c,c,0] # where to save checkpoints (output of i-th block). c: cpu, i(int): cuda:i
    block_dvc_y3: [c,c,c,c] # where to save chkpt (x_fno+x_skip_fno)
    block_dvc_y0: [c,c,c,c] # where to save chkpt (x_fno+x_skip_mlp)
    block_mlp_split: [4,4,4,4] # the i-th element refers to the number of for loops when splitting tensor computation in mlp within the i-th fno block
    block_fft_split: [1,1,1,1] # the i-th element refers to the number of for loops when splitting tensor computation in fft within the i-th fno block

    layer_dvc: [0,0] #lifting/projection layer: where to save checkpoints. c: cpu, i(int): cuda:i
    layer_split: 32 #32 # split dim into pieces


  # Optimizer
  opt:
    n_epochs: 60
    epoch_pde: 20 #20 # start using pde loss
    pde_rate_inc: 1.7 # weight of pde_loss will be multiple rate_inc times wvery inc_time epchs
    pde_inc_time: 500
    renew_opt: True
    learning_rate: 4e-3 # 5e-3
    learning_rate_1: 1.2e-3 # 5e-3
    training_loss: ['l2','l2']
    train_loss_func: ['rel','rel']
    use_pde: [0,0] # a[0]: for 1024, a[1] for 128
    pde_lam: 1e-7
    pde_loss_method: t_fc_x_f # t_fc_x_f or t_fd_x_f
    loss_type: 'sum' #'mean' or sum
    weight_decay: 1e-4 #1e-4 # 1e-4
    amp_autocast: False

    scheduler_T_max: 500 # For cosine only, typically take n_epochs
    scheduler_patience: 5 # For ReduceLROnPlateau only
    scheduler: 'StepLR' # Or 'CosineAnnealingLR' OR 'ReduceLROnPlateau'
    step_size: 15 #60
    gamma: 0.6 #0.5

    check_mem: 0
    gradient_accumulation: 4
    quick_save: 0

  # Dataset related
  data:
    batch_size: 4 #4
    pino2_batch_num: 2 #K128
    pino2_batch_lambda: 1 # lam128
    pino2_btz_lam:
      scale: 15 #lambda decrease every _ epoch
      gamma: 0.5
      end_scale: 60 # no lmbda change after _ epoch
  
    test_resolutions: ['256test','32test']  #only used as wandb plot label
    test_batch_sizes: [8,8]
    num_data: [2000,384,16,16] #les:32, pde:1200
    resolution: [32,256,256,32] #[256,pde,2048,256,2048]
    t_start: [0,0,0,0]  #phy time
    t_interval: [3,3,2,5] #[0.375,0.0625,0.25,0.25,0.25] #if 0: only choose one t0.
    train_tag: [1,1,0,0] #[1,1,1,0,0] #2: test on train set
    dns_dsp: 1


    t_predict: 0.5  #phy time
    traj_for_train: [96,1] #100 in total for N=16, 10 for n=128
    # train_on_testset: 0 #testing on the training set:1. else(normal): 0
    positional_encoding: True
    encode_input: False
    encode_output: False

    t_step_min: 32
    repeat: 1

  # Patching
  patching:
    levels: 0
    padding: 0
    stitching: False

  # Weights and biases
  wandb:
    log: True
    name: None # If None, config will be used but you can override it here
    group: '' 
    project: # add project name here
    entity:  # add your username here
    sweep: False
    log_output: True
    log_test_interval: 1
    pde: kf
    pino: 1
    loss: frs #cgs, frs, pde: the loss function to three stages
    savemd: 0 #True
    model_use: 0 
    model_use_type: 1 # Model after stage 1: supervised loss with CGS data. Model after stage 2: supervised loss with FRS data. Model after stage 3: pde loss